/* Auto-generated by update-gallery.py — do not edit by hand. */
window.GALLERY_IMAGES = [
  "img/gallery/1.jpg",
  "img/gallery/2.jpg",
  "img/gallery/3.jpg",
  "img/gallery/4.jpg",
  "img/gallery/5.jpg",
  "img/gallery/6.jpg",
  "img/gallery/7.jpg",
  "img/gallery/IMG_20150824_121128.jpg",
  "img/gallery/IMG_20190418_133929.jpg",
  "img/gallery/IMG_20190916_131932.jpg",
  "img/gallery/gal-bad.svg",
  "img/gallery/gal-kjokken.svg",
  "img/gallery/gal-tak.svg",
  "img/gallery/gal-terrasse.svg",
  "img/gallery/gal-uthus.svg",
  "img/gallery/gal-vinduer.svg"
];
