/* Auto-generated by update-gallery.py — do not edit by hand. */
window.GALLERY_IMAGES = [
  "img/gallery/gal-bad.svg",
  "img/gallery/gal-kjokken.svg",
  "img/gallery/gal-tak.svg",
  "img/gallery/gal-terrasse.svg",
  "img/gallery/gal-uthus.svg",
  "img/gallery/gal-vinduer.svg"
];
