#!/usr/bin/env python3
"""
Handymannen update-gallery.py
------------------------------
Scans the `img/gallery/` folder and regenerates `gallery-data.js`.

USAGE:
    Drop your project photos into  img/gallery/   (jpg / png / webp / svg)
    Then run:   python3 update-gallery.py
    Commit everything and push. The gallery fills in automatically.
"""
import os
import json

GALLERY_DIR = "img/gallery"
OUT_FILE = "gallery-data.js"

# Image extensions the gallery supports.
EXTS = {".jpg", ".jpeg", ".png", ".webp", ".svg", ".gif", ".avif"}


def main():
    if not os.path.isdir(GALLERY_DIR):
        print(f"! Folder '{GALLERY_DIR}' not found. Create it and drop images inside.")
        return

    files = sorted(
        f for f in os.listdir(GALLERY_DIR)
        if os.path.splitext(f)[1].lower() in EXTS
    )

    if not files:
        print(f"! No images in '{GALLERY_DIR}'. Add some photos and re-run.")
        return

    urls = [f"{GALLERY_DIR}/{f}" for f in files]
    data = {"images": urls, "count": len(urls)}

    with open(OUT_FILE, "w", encoding="utf-8") as fh:
        fh.write("/* Auto-generated by update-gallery.py — do not edit by hand. */\n")
        fh.write("window.GALLERY_IMAGES = ")
        fh.write(json.dumps(urls, ensure_ascii=False, indent=2))
        fh.write(";\n")

    print(f"✔ Found {len(urls)} image(s) in {GALLERY_DIR}")
    for u in urls:
        print(f"   - {u}")
    print(f"✔ Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
