#!/usr/bin/env python3
"""
Handymannen update-gallery.py
------------------------------
Scans the `img/gallery/` folder and regenerates `gallery-data.js`.

It also **automatically optimizes** the photos so the site loads fast:
- Downscales images larger than MAX_WIDTH (default 1600px) to that width.
- Re-compresses JPG/PNG/WebP to a web-friendly quality.
- Creates a `.webp` copy where possible (smaller files) and lists that.

USAGE:
    Drop your project photos into  img/gallery/   (jpg / png / webp / svg)
    Then run:   python3 update-gallery.py
    Commit everything and push. The gallery fills in automatically.

On GitHub this runs automatically via .github/workflows/gallery.yml —
you never need to run it yourself.
"""
import os
import json

GALLERY_DIR = "img/gallery"
OUT_FILE = "gallery-data.js"

# Image extensions the gallery supports (photos get optimized).
PHOTO_EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".avif"}
# Vector images are copied through as-is.
VECTOR_EXTS = {".svg"}

MAX_WIDTH = 1600   # max pixel width for gallery photos
QUALITY = 82       # JPEG/WebP quality


def optimize_photo(path):
    """Resize + compress an image in place. Returns (new_path, ok)."""
    try:
        from PIL import Image
    except Exception:
        return path, False  # Pillow not installed -> keep original

    try:
        img = Image.open(path)
        img.load()
    except Exception:
        return path, False

    # Only downscale (never upscale small images).
    if img.width > MAX_WIDTH:
        h = int(img.height * (MAX_WIDTH / img.width))
        img = img.resize((MAX_WIDTH, h), Image.LANCZOS)

    # Convert RGBA/P so we can save as JPEG.
    base, _ = os.path.splitext(path)
    ext = os.path.splitext(path)[1].lower()

    if ext in (".jpg", ".jpeg"):
        img = img.convert("RGB")
        img.save(path, "JPEG", quality=QUALITY, optimize=True)
        return path, True

    if ext == ".png":
        # Save a webp copy; keep png only if it has transparency.
        if img.mode in ("RGBA", "LA", "P") and "transparency" in img.info:
            img.save(base + ".webp", "WEBP", quality=QUALITY)
            return base + ".webp", True
        img = img.convert("RGB")
        img.save(path, "JPEG", quality=QUALITY, optimize=True)
        return os.path.splitext(path)[0] + ".jpg", True

    if ext == ".webp":
        img.save(path, "WEBP", quality=QUALITY)
        return path, True

    return path, False


def main():
    if not os.path.isdir(GALLERY_DIR):
        print(f"! Folder '{GALLERY_DIR}' not found. Create it and drop images inside.")
        return

    files = sorted(
        f for f in os.listdir(GALLERY_DIR)
        if os.path.splitext(f)[1].lower() in (PHOTO_EXTS | VECTOR_EXTS)
    )

    if not files:
        print(f"! No images in '{GALLERY_DIR}'. Add some photos and re-run.")
        return

    # Optimize photos in place, collecting the final list of files to display.
    final_files = []
    for f in files:
        path = os.path.join(GALLERY_DIR, f)
        ext = os.path.splitext(f)[1].lower()
        if ext in PHOTO_EXTS:
            new_path, ok = optimize_photo(path)
            final_files.append(os.path.basename(new_path))
        else:
            final_files.append(f)

    # Keep unique, sorted.
    final_files = sorted(set(final_files))
    urls = [f"{GALLERY_DIR}/{f}" for f in final_files]

    with open(OUT_FILE, "w", encoding="utf-8") as fh:
        fh.write("/* Auto-generated by update-gallery.py — do not edit by hand. */\n")
        fh.write("window.GALLERY_IMAGES = ")
        fh.write(json.dumps(urls, ensure_ascii=False, indent=2))
        fh.write(";\n")

    total = 0
    for u in urls:
        full = os.path.join(GALLERY_DIR, os.path.basename(u))
        sz = os.path.getsize(full) if os.path.exists(full) else 0
        total += sz
        print(f"   - {u}  ({sz//1024} KB)")
    print(f"✔ Found {len(urls)} image(s) in {GALLERY_DIR}")
    print(f"✔ Total size: {total//1024} KB (≈{total/1024/1024:.1f} MB)")
    print(f"✔ Wrote {OUT_FILE}")


if __name__ == "__main__":
    main()
