<?php
/* ============================================================
   Handymannen – Admin Panel
   ------------------------------------------------------------
   - Simple password login (no database, no user list).
   - After login you can:
       1) Upload photos to the gallery
       2) Delete photos from the gallery
       3) Edit any text on the website
   - All changes are saved to files (content.json, gallery
     folder) and written with PHP, so it works on any normal
     FTP/shared server.
   - The admin password is stored as an encrypted hash
     (bcrypt) in admin/config.php. An unencrypted password is
     never kept on disk.
   ============================================================ */

session_start();

/* -----------------------------------------------------------
   Paths & settings
   ----------------------------------------------------------- */
define('ROOT',        dirname(dirname(__FILE__)));   // site root
define('GALLERY_DIR', ROOT . '/img/gallery');        // photo folder
define('DATA_FILE',   ROOT . '/gallery-data.js');    // image list file
define('CONTENT_FILE',ROOT . '/content.json');       // editable text
define('CONFIG_FILE', __DIR__ . '/config.php');      // password hash

/* -----------------------------------------------------------
   Small helpers
   ----------------------------------------------------------- */
function h($s) { return htmlspecialchars($s, ENT_QUOTES, 'UTF-8'); }

/* Read the password hash from config.php (if it exists). */
function get_password_hash() {
  if (!file_exists(CONFIG_FILE)) return '';
  $cfg = include CONFIG_FILE;
  return is_array($cfg) && isset($cfg['password_hash']) ? $cfg['password_hash'] : '';
}

/* Save the password hash to config.php. */
function save_password_hash($hash) {
  $code = "<?php\n// Admin password (bcrypt hash). Generated automatically.\nreturn " . var_export(array('password_hash' => $hash), true) . ";\n";
  return @file_put_contents(CONFIG_FILE, $code) !== false;
}

/* Read all editable text from content.json. */
function get_content() {
  if (!file_exists(CONTENT_FILE)) return array();
  $data = json_decode(file_get_contents(CONTENT_FILE), true);
  return is_array($data) ? $data : array();
}

/* Write editable text back to content.json. */
function save_content($data) {
  return @file_put_contents(CONTENT_FILE, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)) !== false;
}

/* List image files in the gallery folder. */
function get_gallery_images() {
  $out = array();
  if (is_dir(GALLERY_DIR)) {
    foreach (scandir(GALLERY_DIR) as $f) {
      if ($f === '.' || $f === '..') continue;
      $ext = strtolower(pathinfo($f, PATHINFO_EXTENSION));
      if (in_array($ext, array('jpg','jpeg','png','webp','gif','svg','avif'))) $out[] = $f;
    }
  }
  sort($out, SORT_NATURAL);
  return $out;
}

/* Rebuild gallery-data.js from the current folder contents.
   This keeps the website in sync without needing Python. */
function rebuild_gallery_data() {
  $images = get_gallery_images();
  $list = array();
  foreach ($images as $f) $list[] = 'img/gallery/' . $f;
  $js = "// Auto-generated by the admin panel – do not edit.\nwindow.GALLERY_IMAGES = " . json_encode($list) . ";\n";
  return @file_put_contents(DATA_FILE, $js) !== false;
}

/* Is the visitor logged in? */
function is_logged_in() { return !empty($_SESSION['admin_ok']); }

/* Logged-in check for POST actions. */
function require_login() {
  if (!is_logged_in()) {
    header('Location: index.php');
    exit;
  }
}

/* -----------------------------------------------------------
   Handle actions (only runs on POST)
   ----------------------------------------------------------- */
$message = '';
$error   = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
  $action = isset($_POST['action']) ? $_POST['action'] : '';

  /* ---------- Set password on first run ---------- */
  if ($action === 'setup' && !get_password_hash()) {
    $p1 = isset($_POST['pass1']) ? $_POST['pass1'] : '';
    $p2 = isset($_POST['pass2']) ? $_POST['pass2'] : '';
    if (strlen($p1) < 6) {
      $error = 'Password must be at least 6 characters.';
    } elseif ($p1 !== $p2) {
      $error = 'The two passwords do not match.';
    } else {
      save_password_hash(password_hash($p1, PASSWORD_DEFAULT));
      $message = 'Password created. Please log in.';
    }
  }

  /* ---------- Log in ---------- */
  elseif ($action === 'login' && get_password_hash()) {
    $p = isset($_POST['password']) ? $_POST['password'] : '';
    if (password_verify($p, get_password_hash())) {
      session_regenerate_id(true);
      $_SESSION['admin_ok'] = true;
      $message = 'Welcome, you are logged in.';
    } else {
      $error = 'Wrong password. Try again.';
    }
  }

  /* ---------- Log in (if no password set yet, send to setup) ---------- */
  elseif ($action === 'login' && !get_password_hash()) {
    $error = 'No password has been set yet. Please create one below.';
  }

  /* ---------- Log out ---------- */
  elseif ($action === 'logout') {
    session_destroy();
    header('Location: index.php');
    exit;
  }

  /* ---------- Upload photos ---------- */
  elseif ($action === 'upload' && is_logged_in()) {
    require_login();
    if (empty($_FILES['photos'])) {
      $error = 'No files selected.';
    } else {
      $allowed = array('jpg','jpeg','png','webp','gif','svg','avif');
      $count = 0;
      $files = $_FILES['photos'];
      $total = is_array($files['name']) ? count($files['name']) : 0;
      for ($i = 0; $i < $total; $i++) {
        if ($files['error'][$i] !== UPLOAD_ERR_OK) continue;
        $ext = strtolower(pathinfo($files['name'][$i], PATHINFO_EXTENSION));
        if (!in_array($ext, $allowed)) continue;
        // Use a safe, unique filename.
        $name = preg_replace('/[^A-Za-z0-9_\-]/', '_', pathinfo($files['name'][$i], PATHINFO_FILENAME));
        $dest = GALLERY_DIR . '/' . $name . '.' . $ext;
        $n = 1;
        while (file_exists($dest)) { $dest = GALLERY_DIR . '/' . $name . '_' . $n . '.' . $ext; $n++; }
        if (move_uploaded_file($files['tmp_name'][$i], $dest)) $count++;
      }
      rebuild_gallery_data();
      $message = $count . ' photo(s) uploaded.';
    }
  }

  /* ---------- Delete a photo ---------- */
  elseif ($action === 'delete' && is_logged_in()) {
    require_login();
    $file = basename(isset($_POST['file']) ? $_POST['file'] : '');
    $path = GALLERY_DIR . '/' . $file;
    if ($file !== '' && is_file($path) && strpos(realpath($path), realpath(GALLERY_DIR)) === 0) {
      unlink($path);
      rebuild_gallery_data();
      $message = 'Deleted "' . $file . '".';
    } else {
      $error = 'Could not delete that file.';
    }
  }

  /* ---------- Save edited text ---------- */
  elseif ($action === 'save_text' && is_logged_in()) {
    require_login();
    // Only accept keys that already exist in content.json (avoids junk).
    $content = get_content();
    $saved = 0;
    foreach ($content as $key => $val) {
      if (isset($_POST['field'][$key])) {
        $content[$key] = $_POST['field'][$key];
        $saved++;
      }
    }
    save_content($content);
    $message = $saved . ' text field(s) saved.';
  }
}

/* -----------------------------------------------------------
   Decide which screen to show
   ----------------------------------------------------------- */
$logged_in = is_logged_in();
$has_pass  = (bool) get_password_hash();
$content   = get_content();
$images    = get_gallery_images();

/* A few of the content keys need to render as HTML; these get a textarea. */
$pure_text_keys = array(
  'meta_title','meta_description',
  'stat_jobs_label','stat_score_label','stat_evals_label','stat_refs_label',
  'about_li1','about_li2','about_li3','about_li4','about_cta','about_badge_num',
  'reviews_eyebrow','reviews_heading','areas_more','contact_hint',
  'contact_email_label','contact_email_value','contact_phone_label','contact_phone_value',
  'contact_insta_label','contact_insta_value','contact_addr_label','contact_addr_value',
  'contact_org_label','contact_org_value'
);
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Admin – Handymannen</title>
<style>
  :root { --blue:#01c1ee; --navy:#0f1b3d; --red:#ff3a2e; --muted:#5a6478; --line:#e4e8f0; }
  * { box-sizing:border-box; }
  body { margin:0; font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; background:#f2f5fa; color:#1c2333; line-height:1.5; }
  a { color:var(--blue); }
  .wrap { max-width:980px; margin:0 auto; padding:28px 20px 60px; }
  header { display:flex; align-items:center; justify-content:space-between; gap:16px; margin-bottom:24px; }
  header h1 { font-size:22px; margin:0; }
  header .sub { color:var(--muted); font-size:13px; }
  .card { background:#fff; border:1px solid var(--line); border-radius:14px; padding:26px; margin-bottom:18px; box-shadow:0 6px 18px rgba(15,27,61,.05); }
  .card h2 { margin:0 0 16px; font-size:18px; }
  .btn { display:inline-block; border:0; border-radius:10px; padding:11px 18px; font-size:14px; font-weight:600; cursor:pointer; text-decoration:none; }
  .btn-primary { background:var(--blue); color:#fff; }
  .btn-danger { background:#fff; color:var(--red); border:1px solid #f3c1be; }
  .btn-ghost { background:#eef1f7; color:#333; }
  .btn:hover { opacity:.92; }
  input[type=password], input[type=text], textarea { width:100%; border:1px solid var(--line); border-radius:8px; padding:10px 12px; font:inherit; }
  textarea { min-height:74px; resize:vertical; }
  label { font-size:13px; font-weight:600; color:#384156; display:block; margin:14px 0 6px; }
  .msg { padding:12px 16px; border-radius:8px; margin-bottom:18px; font-size:14px; }
  .msg.ok { background:#e6f8fd; color:#0b6d8a; border:1px solid #b6ecf7; }
  .msg.err { background:#ffe6e2; color:#a22; border:1px solid #f6c1bb; }
  table { width:100%; border-collapse:collapse; }
  th,td { text-align:left; padding:8px 10px; border-bottom:1px solid var(--line); font-size:14px; vertical-align:middle; }
  .thumb { width:70px; height:54px; object-fit:cover; border-radius:6px; border:1px solid var(--line); }
  .tags { margin-top:10px; }
  .tag { display:inline-block; background:#eef1f7; border-radius:6px; padding:3px 8px; font-size:12px; margin:2px; color:#333; }
  .grid2 { display:grid; grid-template-columns:1fr 1fr; gap:0 20px; }
  @media (max-width:640px){ .grid2 { grid-template-columns:1fr; } .btn { width:100%; text-align:center; } }
  .hint { font-size:12px; color:var(--muted); }
  .center { text-align:center; }
  .login-body { max-width:420px; margin:60px auto; }
  .actions { display:flex; gap:10px; flex-wrap:wrap; margin-top:8px; }
</style>
</head>
<body>

<?php if (!$logged_in): ?>
  <!-- ================= LOGIN / SETUP SCREEN ================= -->
  <div class="wrap login-body">
    <div class="card">
      <h1 class="center">Admin – Handymannen</h1>
      <p class="hint center">Log in with the admin password to edit the website.</p>

      <?php if ($message): ?><div class="msg ok"><?= h($message) ?></div><?php endif; ?>
      <?php if ($error):   ?><div class="msg err"><?= h($error) ?></div><?php endif; ?>

      <?php if (!$has_pass): ?>
        <!-- First run: create a password -->
        <form method="post" action="index.php">
          <input type="hidden" name="action" value="setup" />
          <label>New password (min 6 characters)</label>
          <input type="password" name="pass1" autocomplete="new-password" required />
          <label>Repeat password</label>
          <input type="password" name="pass2" autocomplete="new-password" required />
          <div class="actions">
            <button class="btn btn-primary" type="submit">Create password</button>
          </div>
        </form>
      <?php else: ?>
        <!-- Normal login -->
        <form method="post" action="index.php">
          <input type="hidden" name="action" value="login" />
          <label>Password</label>
          <input type="password" name="password" autocomplete="current-password" required />
          <div class="actions">
            <button class="btn btn-primary" type="submit">Log in</button>
          </div>
        </form>
      <?php endif; ?>
    </div>
  </div>

<?php else: ?>
  <!-- ================= ADMIN DASHBOARD ================= -->
  <div class="wrap">
    <header>
      <div>
        <h1>Admin – Handymannen</h1>
        <div class="sub">Edit your website photos and text.</div>
      </div>
      <form method="post" action="index.php"><input type="hidden" name="action" value="logout" /><button class="btn btn-ghost" type="submit">Log out</button></form>
    </header>

    <?php if ($message): ?><div class="msg ok"><?= h($message) ?></div><?php endif; ?>
    <?php if ($error):   ?><div class="msg err"><?= h($error) ?></div><?php endif; ?>

    <!-- ---------- 1. PHOTOS ---------- -->
    <div class="card">
      <h2>Photos</h2>

      <form method="post" action="index.php" enctype="multipart/form-data">
        <input type="hidden" name="action" value="upload" />
        <label>Upload photos (you can select several at once)</label>
        <input type="file" name="photos[]" accept="image/*" multiple />
        <div class="actions">
          <button class="btn btn-primary" type="submit">Upload</button>
        </div>
      </form>

      <table>
        <thead><tr><th>Preview</th><th>File name</th><th>Action</th></tr></thead>
        <tbody>
          <?php foreach ($images as $f): ?>
          <tr>
            <td><img class="thumb" src="../img/gallery/<?= h($f) ?>" alt="" /></td>
            <td><?= h($f) ?></td>
            <td>
              <form method="post" action="index.php" onsubmit="return confirm('Delete this photo?');">
                <input type="hidden" name="action" value="delete" />
                <input type="hidden" name="file" value="<?= h($f) ?>" />
                <button class="btn btn-danger" type="submit">Delete</button>
              </form>
            </td>
          </tr>
          <?php endforeach; if (empty($images)): ?>
          <tr><td colspan="3" class="hint">No photos yet. Upload some above.</td></tr>
          <?php endif; ?>
        </tbody>
      </table>
    </div>

    <!-- ---------- 2. EDIT TEXT ---------- -->
    <div class="card">
      <h2>Edit text</h2>
      <p class="hint">Use HTML tags like <code>&lt;strong&gt;</code> and <code>&lt;em&gt;</code> where you want bold/italic text.</p>
      <form method="post" action="index.php">
        <input type="hidden" name="action" value="save_text" />
        <div class="grid2">
          <?php foreach ($content as $key => $val): ?>
          <div>
            <label for="f_<?= h($key) ?>"><?= h($key) ?></label>
            <?php if (in_array($key, $pure_text_keys)): ?>
              <input type="text" id="f_<?= h($key) ?>" name="field[<?= h($key) ?>]" value="<?= h($val) ?>" />
            <?php else: ?>
              <textarea id="f_<?= h($key) ?>" name="field[<?= h($key) ?>]"><?= h($val) ?></textarea>
            <?php endif; ?>
          </div>
          <?php endforeach; ?>
        </div>
        <div class="actions">
          <button class="btn btn-primary" type="submit">Save text</button>
        </div>
      </form>
    </div>

    <div class="card">
      <h2>Help</h2>
      <ul class="hint">
        <li>Photos are stored in <code>img/gallery/</code> and shown automatically on the website.</li>
        <li>Text changes are saved to <code>content.json</code> and appear on the site.</li>
        <li>To change the password later, delete <code>admin/config.php</code> from the server and reload this page to set a new one.</li>
      </ul>
    </div>
  </div>
<?php endif; ?>
</body>
</html>
